### ISSUE TITLE
Need to add git tag 'v0.4'

### ISSUE THREAD

**Issue by Sajjon** [czechboy0/BuildaUtils#15]
@esttorhe Sorry forgot to tell you, the pod spec is referencing a git tag 'v0.4', I accidentally tagged '0.4' (without the 'v') in my fork, but it does not seam like tags get transfered between forks/pull requests. 

So you need to perform:
`git tag 'v0.4' && git push --tags` 
And then the pod should work!

Because I just tried to update the podfile in the XcodeServerSDK project, for which I have a [Swift 3 PR](https://github.com/buildasaurs/XcodeServerSDK/pull/141), so wanna update that PR to referencing the buildasaurs git page instead of my fork for builds. 

But I am getting:

```
in XcodeServerSDK/ on master 
› pod install 
Analyzing dependencies
Pre-downloading: `DVR` from `https://github.com/Sajjon/DVR.git`
[!] Unable to satisfy the following requirements:

- `BuildaUtils (~> 0.4)` required by `Podfile`
```

Yes I should reference buildasaurs DVR as well, I am waiting for merge of my [DVR PR](https://github.com/buildasaurs/DVR/pull/3), but I kind of broke DVR I think, but at least it compiles :P 

So there is a little bit more work having to be done for DVR.

**Comment by esttorhe** [comment]
yes i noticed. I'm currently trying to release a new pod but i'm having some issues.

I'll try to fix and release it but if not it'll have to wait until after 6:30pm when i get back home

**Comment by esttorhe** [comment]
OK, version `0.4.0` was just released!!

🍞 fresh out of the oven! :)

I'm closing this now. Try it out and if it doesn't work let me know by opening a new issue
