### ISSUE TITLE
Separate date formatter from JSON

### ISSUE THREAD

**Issue by cojoj** [czechboy0/BuildaUtils#2]
Right now we need `NSDateFormatter` located in JSON in other places too.

I think `NSDictionary extension` is not the best place for this and I propose moving this to somewhere else... Maybe `NSDateFormatter extension`? So we'd have this `class func` called `xcsFormatter` or something.

I'm opened for proposals - for naming and also for location.
And **Yes**, I can implement this 😉

**Comment by czechboy0** [comment]
Why not a `NSDate` class extension? So you'd call `NSDate.dateFromBlah(blah)`.

**Comment by cojoj** [comment]
`NSDate.dateFromXCSString("")`?
I'm also thinking about using this in `JSON` and it seems it'll work this way.

**Comment by czechboy0** [comment]
:+1:

**Comment by cojoj** [comment]
Just waiting for a new `tag` so the `Podfile` can download a new version 😉

**Comment by czechboy0** [comment]
Done, 0.0.7: https://cocoapods.org/pods/BuildaUtils
